Questions = \
["What is the bias-variance trade-off?",
"Which factors dominate the model's error at which stages?",
"What is the bias-variance trade-off?",
"Illustrate how the specific model achieves the bias-variance trade-off with examples.",
"What is a confusion matrix?",
"What kind of problems are the confusion matrix used for?",
"What can be derived from the confusion matrix?",
"What is the correlation and covariance in statistics?",
"What is the plot of large negative covariance be like?",
"What is the plot of nearly zero covariance be like?",
"What is the plot of large positive covariance be like?",
"What is the plot of positive correlation be like?",
"What is the plot of zero correlation be like?",
"What is the plot of negative correlation be like?",
"What is the p-value?"
"Based on what kind of the behavior of p-value, we accept and reject the null hypothesis?",
"How to avoid the overfitting and underfitting?",
"What is the selection bias?",
"What is the best ideal ROC curve be like?",
"What is the formula of Softmax function?",
"How much of the time does data pre-processing take?" ,
"What classification algorithms does classifier include? List concrete algorithm(s) under each classification algorithm class.",
"Which algorithm can solve the case with both numerical and categorical data being involved?",
"What is the separating hyperlane?",
"What's the equation of the separating hyperlane for SVM?",
"Give a concrete example of the decision tree.",
"What is the containment relationship between the artificial inteligence, machine learning and deep learning?",
 ]
